/* eslint-disable */
/* prettier-ignore */
/* oxlint-disable */
/* oxfmt-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const Activity: typeof import('react').Activity
  const Fragment: typeof import('react').Fragment
  const Suspense: typeof import('react').Suspense
  const cache: typeof import('react').cache
  const cacheSignal: typeof import('react').cacheSignal
  const createContext: typeof import('react').createContext
  const createPortal: typeof import('react-dom').createPortal
  const createRef: typeof import('react').createRef
  const flushSync: typeof import('react-dom').flushSync
  const forwardRef: typeof import('react').forwardRef
  const lazy: typeof import('react').lazy
  const memo: typeof import('react').memo
  const preconnect: typeof import('react-dom').preconnect
  const prefetchDNS: typeof import('react-dom').prefetchDNS
  const preinit: typeof import('react-dom').preinit
  const preinitModule: typeof import('react-dom').preinitModule
  const preload: typeof import('react-dom').preload
  const preloadModule: typeof import('react-dom').preloadModule
  const startTransition: typeof import('react').startTransition
  const use: typeof import('react').use
  const useActionState: typeof import('react').useActionState
  const useBoolean: typeof import('ahooks').useBoolean
  const useCallback: typeof import('react').useCallback
  const useContext: typeof import('react').useContext
  const useDebounceFn: typeof import('ahooks').useDebounceFn
  const useDebugValue: typeof import('react').useDebugValue
  const useDeferredValue: typeof import('react').useDeferredValue
  const useEffect: typeof import('react').useEffect
  const useEffectEvent: typeof import('react').useEffectEvent
  const useFormStatus: typeof import('react-dom').useFormStatus
  const useHref: typeof import('react-router').useHref
  const useId: typeof import('react').useId
  const useImperativeHandle: typeof import('react').useImperativeHandle
  const useInRouterContext: typeof import('react-router').useInRouterContext
  const useInsertionEffect: typeof import('react').useInsertionEffect
  const useLayoutEffect: typeof import('react').useLayoutEffect
  const useLocation: typeof import('react-router').useLocation
  const useMemo: typeof import('react').useMemo
  const useMemoizedFn: typeof import('ahooks').useMemoizedFn
  const useMount: typeof import('ahooks').useMount
  const useNavigate: typeof import('react-router').useNavigate
  const useNavigationType: typeof import('react-router').useNavigationType
  const useOptimistic: typeof import('react').useOptimistic
  const useOutlet: typeof import('react-router').useOutlet
  const useOutletContext: typeof import('react-router').useOutletContext
  const useParams: typeof import('react-router').useParams
  const useReducer: typeof import('react').useReducer
  const useRef: typeof import('react').useRef
  const useRequest: typeof import('ahooks').useRequest
  const useResolvedPath: typeof import('react-router').useResolvedPath
  const useRoutes: typeof import('react-router').useRoutes
  const useState: typeof import('react').useState
  const useSyncExternalStore: typeof import('react').useSyncExternalStore
  const useTransition: typeof import('react').useTransition
}
